-- Forwarding: the second way to get email into Fortune Cat.
--
-- IMAP asks for an app password, which is one credential that reaches every
-- folder and can send as you. Beta testers refused that screen, and they were
-- right to weigh it. Forwarding asks for nothing: the person hits Forward on a
-- message they chose, and only that message arrives. Sender scoping made the
-- IMAP ask smaller; this removes it entirely for anyone who still says no.
--
-- The token maps an inbound address to exactly one user, mirroring sms_tokens
-- (0010). One difference drives every decision below: THIS TOKEN IS NOT SECRET
-- IN PRACTICE. It travels inside the To: header of every message forwarded
-- with it, so it is visible to mail providers, to anyone else on a forwarded
-- thread, and in any reply chain that quotes headers. Treat it as a public
-- mailbox name, never as a bearer credential.
--
-- What follows from that:
--   * Everything arriving here lands in review. Nothing forwarded ever
--     auto-posts, however trusted the original sender is, because anyone who
--     learns the address can post to it.
--   * The blast radius of a leaked token is "junk appears in my review queue",
--     which is annoying and recoverable. Rotating is a single update.
--   * It grants no read access to anything.
create table if not exists email_forwarding_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  -- The +tag part of the inbound address. URL and email safe, generated by the
  -- app rather than the database so the alphabet stays under our control:
  -- some mail systems lowercase or mangle the local part, so the token must
  -- survive a round trip through case folding.
  token text not null unique check (char_length(token) between 16 and 64),
  last_received_at timestamptz,
  -- Counts messages accepted, so the Capture screen can say "3 forwarded so
  -- far" instead of leaving someone guessing whether it worked at all.
  received_count integer not null default 0,
  -- Gmail's auto-forward confirmation code.
  --
  -- Setting up a Gmail filter to forward automatically makes Google email a
  -- verification code TO THE DESTINATION — an address whose inbox the person
  -- cannot open, because it is ours. Without catching that code here the
  -- auto-forward path is not merely awkward, it is impossible to finish, and
  -- everyone attempting it stalls at the same step with no way forward.
  --
  -- So the webhook recognises Google's confirmation mail, lifts the code, and
  -- parks it here for the Capture screen to display. It is a short-lived
  -- setup value, not a credential, and it is cleared once used.
  pending_confirmation_code text,
  pending_confirmation_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists email_forwarding_tokens_token_idx on email_forwarding_tokens(token);

alter table email_forwarding_tokens enable row level security;

-- Owner-only, same shape as sms_tokens. The webhook reads this table through
-- the admin client (service role, RLS bypassed) because an inbound message
-- arrives with no session — that path is the only reason a lookup by token
-- exists, and it never returns the row to a caller.
drop policy if exists "email_forwarding_owner_select" on email_forwarding_tokens;
create policy "email_forwarding_owner_select" on email_forwarding_tokens
  for select using (auth.uid() = user_id);

drop policy if exists "email_forwarding_owner_insert" on email_forwarding_tokens;
create policy "email_forwarding_owner_insert" on email_forwarding_tokens
  for insert with check (auth.uid() = user_id);

drop policy if exists "email_forwarding_owner_update" on email_forwarding_tokens;
create policy "email_forwarding_owner_update" on email_forwarding_tokens
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "email_forwarding_owner_delete" on email_forwarding_tokens;
create policy "email_forwarding_owner_delete" on email_forwarding_tokens
  for delete using (auth.uid() = user_id);
